### ISSUE TITLE
timeout connecting to port 443

### ISSUE THREAD

**Issue by cheezecat** [AnalogJ/gitmask#10]
Is this service dead?

> $ git push gitmask properSilent
fatal: unable to access 'https://git.gitmask.com/xxx/xxx.git/': Failed to connect to git.gitmask.com port 443: Timed out

**Comment by AnalogJ** [comment]
Yeah, unfortunately its not running right now. I'm looking for another way to host it.

**Comment by AnalogJ** [comment]
@cheezecat @thanatos-tshock 

Gitmask is live once again. The instructions have changed slightly as I now use a serverless lambda to process a `git bundle`, but its still pretty straightforward. 

Check https://www.gitmask.com the an updated example.

**Comment by aepinilla** [comment]
Hi. Is Gitmask running? It has worked for me a couple weeks ago, but now I am getting this error: 

unable to access 'https://git.gitmask.com/v1/gh/xxxxx/xxxx/': The requested URL returned error: 403
