### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rugk** [AnalogJ/gitmask#29]
You need it… https://doesmysiteneedhttps.com/

Why you should always use HTTPS (no matter whether the site is static etc.):
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by AnalogJ** [comment]
Hey,
You're 100% right. The Gitmask landing page has HTTPS, but its not auto-redirecting HTTP->HTTPS. I'll fix that. 

The upload url for gitmask forces HTTPS already, so we're good there. 

-Jason

**Comment by AnalogJ** [comment]
finally fixed.
