### ISSUE TITLE
Add option to leave original author

### ISSUE THREAD

**Issue by j-rewerts** [AnalogJ/gitmask#46]
This may be pushing GitMask beyond its intended purpose. I'm currently looking at Git Mask to allow submitting pull requests without a GitHub account. I actually want the Git author left alone. We could add an optional param that allows this to be configured per request.

I'd be willing to submit a PR if this was considered useful.

**Comment by AnalogJ** [comment]
Not sure what you mean by left alone? The original author is completely
anonymized in the PR so I think gitmask already does what you want, unless
I'm misunderstanding something.

**Comment by j-rewerts** [comment]
Yeah I want the original author to be left in. I feel like I might be confusing you because it's pretty much against the purpose of the app. 😆 

I'm trying to allow people to edit files in GitHub without having an account. We actually have their email though, and it would be nice to know it. No worries if this doesn't seem sensible for you. 

If it's still confusing, I can try submitting a PR with it done.
