### ISSUE TITLE
Add possibility to add PR comment

### ISSUE THREAD

**Issue by sraedler** [AnalogJ/gitmask#47]
Could you please add a parameter, to add a PR comment?

Why? Because sometimes it is necessary to add a comment to understand the purpose of the Pull Request.

**Comment by AnalogJ** [comment]
Hey @sraedler 
Unfortunately the way gitmask v1 is designed, its not very easy to do that. 
I'm working on an update to gitmask that acts as a git remote, which means that you can send extra flags/options to the gitmask api, allowing for custom PR messages and other configuration.

you can follow the progress here: https://github.com/AnalogJ/gitmask/tree/beta

**Comment by sraedler** [comment]
Awesome!
I will follow the progress!

**Comment by AnalogJ** [comment]
Hey @sraedler 
I've updated Gitmask with the `beta` branch, finally adding `git remote` compatibility.
In the next couple of weeks I'll be adding a support for anonymous github pr comments.

**Comment by sraedler** [comment]
Awesome!!!
