### ISSUE TITLE
GitMask without Git/GitHub

### ISSUE THREAD

**Issue by ghost** [AnalogJ/gitmask#76]
Is there a way to use this program to erase file metadata without using `git` or GitHub? It appears to be dependent based on the code instructions from the `README`.

**Comment by AnalogJ** [comment]
not sure I understand what your intent is. This program removes metadata stored in Git commits, `git` is required. 
It doesnt require Github, but Github is the only supported git hosting service currently (GitLab and/or bitbucket support can be added later). 

What file metadata did you want to strip out exactly?

**Comment by ghost** [comment]
Author info and such if it's possible. I just thought of running it on files that I was going to share.
