### ISSUE TITLE
Issue with DockerFile

### ISSUE THREAD

**Issue by anmolnagpal** [AnalogJ/gitmask#8]
Hi,

Using DockerFile i created a docker Image, Http was working fine. but getting error with https://

while creating image got this error. Also when i looked into the docker's "/srv/letsencrypt/" certs folder was missing.

###Error:

Removing intermediate container f306e91bdab5
Step 5 : RUN curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7
 ---> Running in 89f87683332f
Collecting pip
/tmp/tmp9EMMYE/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
/tmp/tmp9EMMYE/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  Downloading pip-8.0.2-py2.py3-none-any.whl (1.2MB)
Collecting setuptools
  Downloading setuptools-19.7-py2.py3-none-any.whl (472kB)
Collecting wheel
  Downloading wheel-0.26.0-py2.py3-none-any.whl (63kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.0.2 setuptools-19.7 wheel-0.26.0
/tmp/tmp9EMMYE/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
 ---> 10c2e361ddda
Removing intermediate container 89f87683332f
Step 6 : RUN sudo pip install --pre github3.py
 ---> Running in b5fa50bc4268
Collecting github3.py
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by AnalogJ** [comment]
That last message is a warning, not an error. Can you post the full logs?
